---
services:
    web:
        container_name: "wp_choice_login_web"
        build:
            args:
                WORDPRESS_VERSION: "${WORDPRESS_VERSION}"
            context: "."
        restart: "always"
        ports:
            - "${WEB_PORT}:80"
        depends_on:
            db:
                condition: "service_healthy"
        environment:
            DB_CHARSET: "utf8mb4"
            DB_COLLATE: "utf8mb4_0900_ai_ci"
            DB_HOST: "db"
            DB_NAME: "wp_choice_login"
            DB_PASSWORD: "wp_choice_login"
            DB_USER: "wp_choice_login"
            WP_SITEURL: "http://localhost:${WEB_PORT}/"
        volumes:
            - "./docker/wp-config.php:/var/www/html/wp-config.php"
            - "./plugin.php:/var/www/html/wp-content/plugins/wp-choice-login/plugin.php"
            - "./src/:/var/www/html/wp-content/plugins/wp-choice-login/src/"

    db:
        container_name: "wp_choice_login_db"
        image: "mysql:8.3.0"
        restart: "always"
        ports:
            - "8001:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        environment:
            MYSQL_DATABASE: "wp_choice_login"
            MYSQL_USER: "wp_choice_login"
            MYSQL_PASSWORD: "wp_choice_login"
            MYSQL_ROOT_PASSWORD: "wp_choice_login"
