name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    ci:
        name: "CI (php v${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version: [ "8.2", "8.3" ]

        steps:
            -   name: "Checkout Code"
                uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
            -   name: "Setup PHP"
                uses: "shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d"
                with:
                    php-version: "${{ matrix.php-version }}"
                    tools: "composer"
            -   name: "Install Dependencies"
                run: "make install"
            -   name: "Run Code Format Checks"
                run: "make lint"
            -   name: "Run Test Suite"
                run: "make test"
